
import os
import main
try:
    main.run()
except Exception as e:
    print(e)
